
project_id = "bdhxrmfyewzyhthrwnyq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"

[storage]
enabled = true

[edge_functions]
enabled = true

[functions.setup-initial-users]
verify_jwt = false

[functions.setup-demo-data]
verify_jwt = false
